import wine from "./img/wine.png";
import flag from "./img/flag.png";
import sparklingPhoto from "./img/sparkling.png"
import whiskyPhoto from './img/whisky.png'

const wines = [
    {   id: 1,
        name: 'L’ERMITE HERMITAGE 1',
        color: 'Белое',
        sweetness: 'Полусладкое',
        grapeSort: 'верментино',
        classification: 'тихое вино',
        country: 'Франция',
        area: 'm.chapoutier',
        year: 2009,
        volume: '0.75 л',
        flag: flag,
        price: 1500,
        photo: wine
    },
    {   id: 2,
        name: 'L’ERMITE HERMITAGE 2',
        color: 'Красное',
        sweetness: 'Полусухое',
        grapeSort: 'верментино',
        classification: 'Тихое вино',
        country: 'Италия',
        area: 'm.chapoutier',
        year: 2009,
        volume: '0.75 л',
        flag: flag,
        price: 2500,
        photo: wine
    },
    {   id: 3,
        name: 'L’ERMITE HERMITAGE 3',
        color: 'Розовое',
        sweetness: 'Сухое',
        grapeSort: 'верментино',
        classification: 'тихое вино',
        country: 'Франция',
        area: 'm.chapoutier',
        year: 2009,
        volume: '0.75 л',
        flag: flag,
        price: 3500,
        photo: wine
    },
    {   id: 4,
        name: 'L’ERMITE HERMITAGE 4',
        color: 'Красное',
        sweetness: 'Сладкое',
        grapeSort: 'Верментино',
        classification: 'Тихое вино',
        country: 'Италия',
        area: 'm.chapoutier',
        year: 2009,
        volume: '0.75 л',
        flag: flag,
        price: 4500,
        photo: wine
    },
    {   id: 5,
        name: 'L’ERMITE HERMITAGE 5',
        color: 'Белое',
        sweetness: 'Полусладкое',
        grapeSort: 'верментино',
        classification: 'тихое вино',
        country: 'Франция',
        area: 'm.chapoutier',
        year: 2009,
        volume: '0.75 л',
        flag: flag,
        price: 1500,
        photo: wine
    },
    {   id: 6,
        name: 'L’ERMITE HERMITAGE 6',
        color: 'Красное',
        sweetness: 'Полусухое',
        grapeSort: 'верментино',
        classification: 'Тихое вино',
        country: 'Италия',
        area: 'm.chapoutier',
        year: 2009,
        volume: '0.75 л',
        flag: flag,
        price: 2500,
        photo: wine
    },
    {   id: 7,
        name: 'L’ERMITE HERMITAGE 7',
        color: 'Розовое',
        sweetness: 'Сухое',
        grapeSort: 'верментино',
        classification: 'тихое вино',
        country: 'Франция',
        area: 'm.chapoutier',
        year: 2009,
        volume: '0.75 л',
        flag: flag,
        price: 3500,
        photo: wine
    },
    {   id: 8,
        name: 'L’ERMITE HERMITAGE 8',
        color: 'Красное',
        sweetness: 'Сладкое',
        grapeSort: 'Верментино',
        classification: 'Тихое вино',
        country: 'Италия',
        area: 'm.chapoutier',
        year: 2009,
        volume: '0.75 л',
        flag: flag,
        price: 4500,
        photo: wine
    },
    {   id: 9,
        name: 'L’ERMITE HERMITAGE 9',
        color: 'Красное',
        sweetness: 'Сладкое',
        grapeSort: 'Верментино',
        classification: 'Тихое вино',
        country: 'Италия',
        area: 'm.chapoutier',
        year: 2009,
        volume: '0.75 л',
        flag: flag,
        price: 4500,
        photo: wine
    },
    {   id: 10,
        name: 'L’ERMITE HERMITAGE 10',
        color: 'Белое',
        sweetness: 'Полусладкое',
        grapeSort: 'верментино',
        classification: 'тихое вино',
        country: 'Франция',
        area: 'm.chapoutier',
        year: 2009,
        volume: '0.75 л',
        flag: flag,
        price: 1500,
        photo: wine
    },
    {   id: 11,
        name: 'L’ERMITE HERMITAGE 11',
        color: 'Красное',
        sweetness: 'Полусухое',
        grapeSort: 'верментино',
        classification: 'Тихое вино',
        country: 'Италия',
        area: 'm.chapoutier',
        year: 2009,
        volume: '0.75 л',
        flag: flag,
        price: 2500,
        photo: wine
    },
    {   id: 12,
        name: 'L’ERMITE HERMITAGE 12',
        color: 'Розовое',
        sweetness: 'Сухое',
        grapeSort: 'верментино',
        classification: 'тихое вино',
        country: 'Франция',
        area: 'm.chapoutier',
        year: 2009,
        volume: '0.75 л',
        flag: flag,
        price: 3500,
        photo: wine
    },
    {   id: 13,
        name: 'L’ERMITE HERMITAGE 13',
        color: 'Красное',
        sweetness: 'Сладкое',
        grapeSort: 'Верментино',
        classification: 'Тихое вино',
        country: 'Италия',
        area: 'm.chapoutier',
        year: 2009,
        volume: '0.75 л',
        flag: flag,
        price: 4500,
        photo: wine
    },
    {   id: 14,
        name: 'L’ERMITE HERMITAGE 14',
        color: 'Белое',
        sweetness: 'Полусладкое',
        grapeSort: 'верментино',
        classification: 'тихое вино',
        country: 'Франция',
        area: 'm.chapoutier',
        year: 2009,
        volume: '0.75 л',
        flag: flag,
        price: 1500,
        photo: wine
    },
    {   id: 15,
        name: 'L’ERMITE HERMITAGE 15',
        color: 'Красное',
        sweetness: 'Полусухое',
        grapeSort: 'верментино',
        classification: 'Тихое вино',
        country: 'Италия',
        area: 'm.chapoutier',
        year: 2009,
        volume: '0.75 л',
        flag: flag,
        price: 2500,
        photo: wine
    },
    {   id: 16,
        name: 'L’ERMITE HERMITAGE 16',
        color: 'Розовое',
        sweetness: 'Сухое',
        grapeSort: 'верментино',
        classification: 'тихое вино',
        country: 'Франция',
        area: 'm.chapoutier',
        year: 2009,
        volume: '0.75 л',
        flag: flag,
        price: 3500,
        photo: wine
    },
    {   id: 17,
        name: 'L’ERMITE HERMITAGE 17',
        color: 'Красное',
        sweetness: 'Сладкое',
        grapeSort: 'Верментино',
        classification: 'Тихое вино',
        country: 'Италия',
        area: 'm.chapoutier',
        year: 2009,
        volume: '0.75 л',
        flag: flag,
        price: 4500,
        photo: wine
    },
    {   id: 18,
        name: 'L’ERMITE HERMITAGE 18',
        color: 'Красное',
        sweetness: 'Сладкое',
        grapeSort: 'Верментино',
        classification: 'Тихое вино',
        country: 'Италия',
        area: 'm.chapoutier',
        year: 2009,
        volume: '0.75 л',
        flag: flag,
        price: 4500,
        photo: wine
    },
]

export default wines;

export const sparkling = [
    {   id: 1,
        name: 'L’ERMITE HERMITAGE 1',
        color: 'Белое',
        sweetness: 'Брют',
        grapeSort: 'верментино',
        kindOfSparkling: 'Асти',
        country: 'Франция',
        area: 'm.chapoutier',
        year: 2009,
        volume: '0.75 л',
        flag: flag,
        price: 500,
        photo: sparklingPhoto
    },
    {   id: 2,
        name: 'L’ERMITE HERMITAGE 1',
        color: 'Белое',
        sweetness: 'Брют',
        grapeSort: 'верментино',
        kindOfSparkling: 'Асти',
        country: 'Франция',
        area: 'm.chapoutier',
        year: 2009,
        volume: '0.75 л',
        flag: flag,
        price: 1500,
        photo: sparklingPhoto
    },
    {   id: 3,
        name: 'L’ERMITE HERMITAGE 1',
        color: 'Белое',
        sweetness: 'Брют',
        grapeSort: 'верментино',
        kindOfSparkling: 'Асти',
        country: 'Франция',
        area: 'm.chapoutier',
        year: 2009,
        volume: '0.75 л',
        flag: flag,
        price: 2500,
        photo: sparklingPhoto
    },
    {   id: 4,
        name: 'L’ERMITE HERMITAGE 1',
        color: 'Белое',
        sweetness: 'Брют',
        grapeSort: 'верментино',
        kindOfSparkling: 'Асти',
        country: 'Франция',
        area: 'm.chapoutier',
        year: 2009,
        volume: '0.75 л',
        flag: flag,
        price: 3500,
        photo: sparklingPhoto
    },
    {   id: 5,
        name: 'L’ERMITE HERMITAGE 1',
        color: 'Белое',
        sweetness: 'Брют',
        grapeSort: 'верментино',
        kindOfSparkling: 'Асти',
        country: 'Франция',
        area: 'm.chapoutier',
        year: 2009,
        volume: '0.75 л',
        flag: flag,
        price: 4500,
        photo: sparklingPhoto
    },
    {   id: 6,
        name: 'L’ERMITE HERMITAGE 1',
        color: 'Белое',
        sweetness: 'Брют',
        grapeSort: 'верментино',
        kindOfSparkling: 'Асти',
        country: 'Франция',
        area: 'm.chapoutier',
        year: 2009,
        volume: '0.75 л',
        flag: flag,
        price: 5500,
        photo: sparklingPhoto
    },
    {   id: 7,
        name: 'L’ERMITE HERMITAGE 1',
        color: 'Белое',
        sweetness: 'Брют',
        grapeSort: 'верментино',
        kindOfSparkling: 'Асти',
        country: 'Франция',
        area: 'm.chapoutier',
        year: 2009,
        volume: '0.75 л',
        flag: flag,
        price: 6500,
        photo: sparklingPhoto
    },
    {   id: 8,
        name: 'L’ERMITE HERMITAGE 1',
        color: 'Белое',
        sweetness: 'Брют',
        grapeSort: 'верментино',
        kindOfSparkling: 'Асти',
        country: 'Франция',
        area: 'm.chapoutier',
        year: 2009,
        volume: '0.75 л',
        flag: flag,
        price: 7500,
        photo: sparklingPhoto
    },
    {   id: 9,
        name: 'L’ERMITE HERMITAGE 9',
        color: 'Белое',
        sweetness: 'Брют',
        grapeSort: 'верментино',
        kindOfSparkling: 'Асти',
        country: 'Франция',
        area: 'm.chapoutier',
        year: 2009,
        volume: '0.75 л',
        flag: flag,
        price: 8500,
        photo: sparklingPhoto
    },
    {   id: 1,
        name: 'L’ERMITE HERMITAGE 1',
        color: 'Белое',
        sweetness: 'Брют',
        grapeSort: 'верментино',
        kindOfSparkling: 'Асти',
        country: 'Франция',
        area: 'm.chapoutier',
        year: 2009,
        volume: '0.75 л',
        flag: flag,
        price: 500,
        photo: sparklingPhoto
    },
    {   id: 2,
        name: 'L’ERMITE HERMITAGE 1',
        color: 'Белое',
        sweetness: 'Брют',
        grapeSort: 'верментино',
        kindOfSparkling: 'Асти',
        country: 'Франция',
        area: 'm.chapoutier',
        year: 2009,
        volume: '0.75 л',
        flag: flag,
        price: 1500,
        photo: sparklingPhoto
    },
    {   id: 3,
        name: 'L’ERMITE HERMITAGE 1',
        color: 'Белое',
        sweetness: 'Брют',
        grapeSort: 'верментино',
        kindOfSparkling: 'Асти',
        country: 'Франция',
        area: 'm.chapoutier',
        year: 2009,
        volume: '0.75 л',
        flag: flag,
        price: 2500,
        photo: sparklingPhoto
    },
    {   id: 4,
        name: 'L’ERMITE HERMITAGE 1',
        color: 'Белое',
        sweetness: 'Брют',
        grapeSort: 'верментино',
        kindOfSparkling: 'Асти',
        country: 'Франция',
        area: 'm.chapoutier',
        year: 2009,
        volume: '0.75 л',
        flag: flag,
        price: 3500,
        photo: sparklingPhoto
    },
    {   id: 5,
        name: 'L’ERMITE HERMITAGE 1',
        color: 'Белое',
        sweetness: 'Брют',
        grapeSort: 'верментино',
        kindOfSparkling: 'Асти',
        country: 'Франция',
        area: 'm.chapoutier',
        year: 2009,
        volume: '0.75 л',
        flag: flag,
        price: 4500,
        photo: sparklingPhoto
    },
    {   id: 6,
        name: 'L’ERMITE HERMITAGE 1',
        color: 'Белое',
        sweetness: 'Брют',
        grapeSort: 'верментино',
        kindOfSparkling: 'Асти',
        country: 'Франция',
        area: 'm.chapoutier',
        year: 2009,
        volume: '0.75 л',
        flag: flag,
        price: 5500,
        photo: sparklingPhoto
    },
    {   id: 7,
        name: 'L’ERMITE HERMITAGE 1',
        color: 'Белое',
        sweetness: 'Брют',
        grapeSort: 'верментино',
        kindOfSparkling: 'Асти',
        country: 'Франция',
        area: 'm.chapoutier',
        year: 2009,
        volume: '0.75 л',
        flag: flag,
        price: 6500,
        photo: sparklingPhoto
    },
    {   id: 8,
        name: 'L’ERMITE HERMITAGE 1',
        color: 'Белое',
        sweetness: 'Брют',
        grapeSort: 'верментино',
        kindOfSparkling: 'Асти',
        country: 'Франция',
        area: 'm.chapoutier',
        year: 2009,
        volume: '0.75 л',
        flag: flag,
        price: 7500,
        photo: sparklingPhoto
    },
    {   id: 9,
        name: 'L’ERMITE HERMITAGE 18',
        color: 'Белое',
        sweetness: 'Брют',
        grapeSort: 'верментино',
        kindOfSparkling: 'Асти',
        country: 'Франция',
        area: 'm.chapoutier',
        year: 2009,
        volume: '0.75 л',
        flag: flag,
        price: 8500,
        photo: sparklingPhoto
    }
]

export const whisky = [
    {
        id: 1,
        name: 'Виски 1',
        typeOfWhisky: 'Бурбон',
        agingPeriod: '3 Year Old',
        bottler: 'Hart Brothers',
        country: 'Франция',
        area: 'm.chapoutier',
        year: 2009,
        volume: '0.75 л',
        flag: flag,
        price: 8500,
        photo: whiskyPhoto
    },
    {
        id: 2,
        name: 'L’ERMITE HERMITAGE 2',
        typeOfWhisky: 'Купажированный',
        agingPeriod: '5 Year Old',
        bottler: 'Douglas Laing',
        country: 'Франция',
        area: 'm.chapoutier',
        year: 2009,
        volume: '0.75 л',
        flag: flag,
        price: 8500,
        photo: whiskyPhoto
    },
    {
        id: 3,
        name: 'L’ERMITE HERMITAGE 3',
        typeOfWhisky: 'Односолодовый',
        agingPeriod: '10 Year Old',
        bottler: 'Gordon & MacPhail',
        country: 'Франция',
        area: 'm.chapoutier',
        year: 2009,
        volume: '0.75 л',
        flag: flag,
        price: 8500,
        photo: whiskyPhoto
    },
    {
        id: 4,
        name: 'L’ERMITE HERMITAGE 4',
        typeOfWhisky: 'Бурбон',
        agingPeriod: '3 Year Old',
        bottler: 'Hart Brothers',
        country: 'Франция',
        area: 'm.chapoutier',
        year: 2009,
        volume: '0.75 л',
        flag: flag,
        price: 8500,
        photo: whiskyPhoto
    },
    {
        id: 5,
        name: 'L’ERMITE HERMITAGE 5',
        typeOfWhisky: 'Купажированный',
        agingPeriod: '5 Year Old',
        bottler: 'Douglas Laing',
        country: 'Франция',
        area: 'm.chapoutier',
        year: 2009,
        volume: '0.75 л',
        flag: flag,
        price: 8500,
        photo: whiskyPhoto
    },
    {
        id: 6,
        name: 'L’ERMITE HERMITAGE 6',
        typeOfWhisky: 'Односолодовый',
        agingPeriod: '10 Year Old',
        bottler: 'Gordon & MacPhail',
        country: 'Франция',
        area: 'm.chapoutier',
        year: 2009,
        volume: '0.75 л',
        flag: flag,
        price: 8500,
        photo: whiskyPhoto
    },
    {
        id: 7,
        name: 'L’ERMITE HERMITAGE 7',
        typeOfWhisky: 'Бурбон',
        agingPeriod: '3 Year Old',
        bottler: 'Hart Brothers',
        country: 'Франция',
        area: 'm.chapoutier',
        year: 2009,
        volume: '0.75 л',
        flag: flag,
        price: 8500,
        photo: whiskyPhoto
    },
    {
        id: 8,
        name: 'L’ERMITE HERMITAGE 8',
        typeOfWhisky: 'Купажированный',
        agingPeriod: '5 Year Old',
        bottler: 'Douglas Laing',
        country: 'Франция',
        area: 'm.chapoutier',
        year: 2009,
        volume: '0.75 л',
        flag: flag,
        price: 8500,
        photo: whiskyPhoto
    },
    {
        id: 9,
        name: 'L’ERMITE HERMITAGE 9',
        typeOfWhisky: 'Односолодовый',
        agingPeriod: '10 Year Old',
        bottler: 'Gordon & MacPhail',
        country: 'Франция',
        area: 'm.chapoutier',
        year: 2009,
        volume: '0.75 л',
        flag: flag,
        price: 8500,
        photo: whiskyPhoto
    },
    {
        id: 10,
        name: 'L’ERMITE HERMITAGE 10',
        typeOfWhisky: 'Бурбон',
        agingPeriod: '3 Year Old',
        bottler: 'Hart Brothers',
        country: 'Франция',
        area: 'm.chapoutier',
        year: 2009,
        volume: '0.75 л',
        flag: flag,
        price: 8500,
        photo: whiskyPhoto
    },
    {
        id: 11,
        name: 'L’ERMITE HERMITAGE 11',
        typeOfWhisky: 'Купажированный',
        agingPeriod: '5 Year Old',
        bottler: 'Douglas Laing',
        country: 'Франция',
        area: 'm.chapoutier',
        year: 2009,
        volume: '0.75 л',
        flag: flag,
        price: 8500,
        photo: whiskyPhoto
    },
    {
        id: 12,
        name: 'L’ERMITE HERMITAGE 12',
        typeOfWhisky: 'Односолодовый',
        agingPeriod: '10 Year Old',
        bottler: 'Gordon & MacPhail',
        country: 'Франция',
        area: 'm.chapoutier',
        year: 2009,
        volume: '0.75 л',
        flag: flag,
        price: 8500,
        photo: whiskyPhoto
    },
    {
        id: 13,
        name: 'L’ERMITE HERMITAGE 13',
        typeOfWhisky: 'Бурбон',
        agingPeriod: '3 Year Old',
        bottler: 'Hart Brothers',
        country: 'Франция',
        area: 'm.chapoutier',
        year: 2009,
        volume: '0.75 л',
        flag: flag,
        price: 8500,
        photo: whiskyPhoto
    },
    {
        id: 14,
        name: 'L’ERMITE HERMITAGE 14',
        typeOfWhisky: 'Купажированный',
        agingPeriod: '5 Year Old',
        bottler: 'Douglas Laing',
        country: 'Франция',
        area: 'm.chapoutier',
        year: 2009,
        volume: '0.75 л',
        flag: flag,
        price: 8500,
        photo: whiskyPhoto
    },
    {
        id: 15,
        name: 'L’ERMITE HERMITAGE 15',
        typeOfWhisky: 'Односолодовый',
        agingPeriod: '10 Year Old',
        bottler: 'Gordon & MacPhail',
        country: 'Франция',
        area: 'm.chapoutier',
        year: 2009,
        volume: '0.75 л',
        flag: flag,
        price: 8500,
        photo: whiskyPhoto
    },
    {
        id: 16,
        name: 'L’ERMITE HERMITAGE 16',
        typeOfWhisky: 'Бурбон',
        agingPeriod: '3 Year Old',
        bottler: 'Hart Brothers',
        country: 'Франция',
        area: 'm.chapoutier',
        year: 2009,
        volume: '0.75 л',
        flag: flag,
        price: 8500,
        photo: whiskyPhoto
    },
    {
        id: 17,
        name: 'L’ERMITE HERMITAGE 17',
        typeOfWhisky: 'Купажированный',
        agingPeriod: '5 Year Old',
        bottler: 'Douglas Laing',
        country: 'Франция',
        area: 'm.chapoutier',
        year: 2009,
        volume: '0.75 л',
        flag: flag,
        price: 8500,
        photo: whiskyPhoto
    },
    {
        id: 18,
        name: 'L’ERMITE HERMITAGE 18',
        typeOfWhisky: 'Односолодовый',
        agingPeriod: '> 20 Year Old',
        bottler: 'Gordon & MacPhail',
        country: 'Франция',
        area: 'm.chapoutier',
        year: 2009,
        volume: '0.75 л',
        flag: flag,
        price: 8500,
        photo: whiskyPhoto
    },
]